version: "3.9"

services:
  tr1g1-front:
    build:
      context: ./front
    restart: always
    ports:
      - 80:80
    depends_on:
      - tr1g1-back
    command: sh -c "npm install && npm run build && http-server dist -p 80"

  tr1g1-back:
    image: node:23-bookworm-slim
    command: sh -c "cp .env.PROD .env && npm install && node index.js"
    volumes:
      - ./back:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000

  tr1g1-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: QUESTIONS
    volumes:
      - mysql-db:/var/lib/mysql:rw
      - ./back/data/create_db.sql:/docker-entrypoint-initdb.d/create.sql
      - ./back/data/insert_db.sql:/docker-entrypoint-initdb.d/inserts.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: tr1g1-mysql
    depends_on:
      - tr1g1-mysql

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443

volumes:
  mysql-db:
  portainer_data:
